apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-config.yaml
  - route-config.yaml

crds:
  - ./crds/openshift-deploymentconfig.json
  - ./crds/openshift-route.json
